server:
  port: 8080
  servlet:
    context-path: /sticky-app
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        max-age: 3600

spring:
  application:
    name: sticky-session-tester

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  server:
    base-path: /sticky-app
  metrics:
    export:
      prometheus:
        enabled: true
