apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - middleware.yaml
  - deployment.yaml
  - service-roundrobin.yaml
  - service-clientip.yaml
  - service-cookie.yaml
  - ingressroute-roundrobin.yaml
  - ingressroute-clientip.yaml
  - ingressroute-cookie.yaml
