apiVersion: v1
kind: Service
metadata:
  name: sticky-tester-roundrobin
  namespace: sticky-session-tester
  labels:
    app: sticky-session-tester
    service-type: roundrobin
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: sticky-session-tester
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
